on:
  push:
    branches:
      - 'master'
      - 'v*'
    paths:
      - 'PKGBUILD'
    tags:
      - 'v*'
  workflow_dispatch:

name: Build PKGBUILD
jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags/')
      - name: PKGBUILD version matches release tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          rc=0
          tag="${{ github.ref }}"
          ver="${tag%%-*}"
          ver="${ver##v}"
          rel="${tag##*-}"
          grep "^pkgver=$ver$" PKGBUILD || {
            echo "pkgver not matching tag";
            rc=1;
          }

          grep "^pkgrel=$rel$" PKGBUILD || {
            echo "pkgrel not matching tag";
            rc=1;
          }
          exit $rc

  build:
    runs-on: ubuntu-latest
    needs: check_tag
    steps:
      - uses: actions/checkout@v3
      - name: Install makedeb
        run: |
          sudo apt update
          sudo apt install -y wget gpg
          wget -qO - 'https://proget.makedeb.org/debian-feeds/makedeb.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg 1> /dev/null
          echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.makedeb.org/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
          sudo apt update
          sudo apt install -y makedeb
      - name: Build PKGBUILD
        run: makedeb -s --no-confirm
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.deb
            PKGBUILD
