on:
  push:
    branches:
      - 'master'
      - 'v*'
    paths:
      - 'PKGBUILD'
    tags:
      - 'v*'
  workflow_dispatch:

name: Build PKGBUILD
jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags/')
      - name: PKGBUILD version matches release tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          rc=0
          tag="${{ github.ref }}"
          ver="${tag%%-*}"
          rel="${tag##*-}"
          grep "^pkgver=$ver$" PKGBUILD || {
            echo "pkgver not matching tag";
            rc=1;
          }

          grep "^pkgrel=$rel$" PKGBUILD || {
            echo "pkgrel not matching tag";
            rc=1;
          }
          exit $rc

  build:
    runs-on: ubuntu-latest
    needs: check_tag
    steps:
      - uses: actions/checkout@v3
      - name: Install makedeb
        run: bash -ci "$(wget -qO - 'https://shlink.makedeb.org/install')"
      - name: Build PKGBUILD
        run: makedeb -s --no-confirm
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.deb
            PKGBUILD
