on:
  push:
    branches:
      - 'master'
      - 'v*'
    paths:
      - 'PKGBUILD'
    tags:
      - 'v*'
  workflow_dispatch:

name: Build PKGBUILD
jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: startsWith(github.ref, 'refs/tags/')
      - name: PKGBUILD version matches release tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          rc=0
          tag="${{ github.ref }}"
          tag="${tag##*/}"
          ver="${tag%-*}"
          ver="${ver#v}"
          rel="${tag##*-}"
          grep "^pkgver=$ver$" PKGBUILD || {
            echo "pkgver not matching tag";
            rc=1;
          }

          grep "^pkgrel=$rel$" PKGBUILD || {
            echo "pkgrel not matching tag";
            rc=1;
          }
          exit $rc

  build:
    runs-on: ubuntu-latest
    needs: check_tag
    container: 
      image: joscherrer/actions-images:makedeb
    steps:
      - uses: actions/checkout@v3

      - name: Run shfmt
        run: shfmt -i 4 -d PKGBUILD

      - name: Run shellcheck
        run: shellcheck -s bash PKGBUILD

      - name: Run makedeb lint
        run: makedeb --lint

      - name: Update apt cache
        run: sudo apt update

      - name: Build PKGBUILD
        run: makedeb -s --no-confirm

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.deb
            PKGBUILD
